const capsuleGrid = document.getElementById("capsule-grid");
const memorySection = document.querySelector(".memory-section");
const memoryMap = document.getElementById("memory-map");
const nowPlayingText = document.getElementById("now-playing");
const persistentPlayer = document.getElementById("persistent-player");
const persistentPlayerImage = document.getElementById("persistent-player-image");
const persistentPlayerFallback = document.getElementById("persistent-player-art-fallback");
const persistentPlayerMapThumb = document.getElementById("persistent-player-map-thumb");
const persistentPlayerTitle = document.getElementById("persistent-player-title");
const persistentPlayerLocation = document.getElementById("persistent-player-location");
const persistentPlayerToggle = document.getElementById("persistent-player-toggle");
const persistentPlayerProgress = document.getElementById("persistent-player-progress");
const persistentPlayerCurrent = document.getElementById("persistent-player-current");
const persistentPlayerDuration = document.getElementById("persistent-player-duration");
const persistentPlayerOpen = document.getElementById("persistent-player-open");
const persistentPlayerInner = document.querySelector(".persistent-player-inner");
const capsuleView = document.getElementById("capsule-view");
const capsuleViewBack = document.getElementById("capsule-view-back");
const capsuleViewMapThumb = document.getElementById("capsule-view-map-thumb");
const capsuleViewMapLoopSlide = document.getElementById("capsule-view-map-loop-slide");
const capsuleViewMapLoopThumb = document.getElementById("capsule-view-map-loop-thumb");
const capsuleVisualCarousel = document.getElementById("capsule-visual-carousel");
const capsuleVisuals = document.getElementById("capsule-visuals");
const capsuleVisualIndicators = document.getElementById("capsule-visual-indicators");
const capsuleVisualNext = document.getElementById("capsule-visual-next");
const capsuleViewPhotoSlide = document.getElementById("capsule-view-photo-slide");
const capsuleViewImage = document.getElementById("capsule-view-image");
const capsuleViewSignature = document.getElementById("capsule-view-signature");
const capsuleViewSignatureToggle = document.getElementById("capsule-signature-toggle");
const capsuleViewSignatureValue = document.getElementById("capsule-view-signature-value");
const capsuleViewSignatureDescription = document.getElementById("capsule-view-signature-description");
const capsuleViewTitle = document.getElementById("capsule-view-title");
const capsuleViewLocation = document.getElementById("capsule-view-location");
const capsuleViewDate = document.getElementById("capsule-view-date");
const capsuleViewDetails = document.getElementById("capsule-view-details");
const leafletMapContainer = document.getElementById("leaflet-map");
const collectionMap = document.getElementById("collection-map");
const mapTitle = document.getElementById("map-title");
const mapSubtitle = document.getElementById("map-subtitle");
const memoryTitle = document.getElementById("memory-title");
const memorySubtitle = document.getElementById("memory-subtitle");
const appNavButtons = document.querySelectorAll("[data-app-section]");
const homeLink = document.getElementById("home-link");
const homeExploreLink = document.getElementById("home-explore-link");
const homeView = document.getElementById("home-view");
const mapSection = document.querySelector(".map-section");
const savedView = document.getElementById("saved-view");
const profileView = document.getElementById("profile-view");
const appContent = document.querySelector(".app-content");
const exploreFilterRow = document.getElementById("explore-filter-row");
const exploreCityMap = document.getElementById("explore-city-map");
let exploreCityLeafletMap = null;

// Start the app navigation, persistent player, and map experience.
setupAppNavigation();
setupHomeInteractions();
setAppSection("home");
setupPersistentPlayer();
initRealMap();